Repository rust379/MApp, pull requests merged in 2021-10, with the labels that each got.

#110 DimensionZeroBug - Add min column count.
  interface/basicForms/mappTable.cpp
Labels: bug

#112 Refactor single selection functions in appointment [patient, service, ...]
  interface/appointment/appointmentForm.cpp
  interface/appointment/appointmentForm.h
Labels: refactoring

#116 MultiColumnSearch - Add MultiColumnSortFilterProxyModel class.
  MApp.pro
  interface/basicForms/components/multiColumnSortFilterProxyModel/multiColumnSortFilterProxyModel.cpp
  interface/basicForms/components/multiColumnSortFilterProxyModel/multiColumnSortFilterProxyModel.h
  interface/basicForms/mappTable.cpp
Labels: enhancement

#111 Refactor files form [use fileViewer interfaces with manager instead of tabWidget]
  MApp.pro
  interface/file/displayWidgets/displayManager.cpp
  interface/file/displayWidgets/displayManager.h
  interface/file/displayWidgets/imageViewer.cpp
  interface/file/displayWidgets/imageViewer.h
  interface/file/displayWidgets/textViewer.cpp
  interface/file/displayWidgets/textViewer.h
  interface/file/displayWidgets/viewerInterface.cpp
  interface/file/displayWidgets/viewerInterface.h
  interface/file/fileForm.cpp
  interface/file/fileForm.h
  interface/file/fileForm.ui
Labels: refactoring

#131 Use text editor in appointment record form
  interface/appointment/appointmentForm.cpp
  interface/appointment/appointmentRecordForm.cpp
  interface/appointment/appointmentRecordForm.h
  interface/appointment/appointmentRecordForm.ui
Labels: enhancement

#127 Image viewer
  MApp.pro
  interface/appointment/appointmentForm.ui
  interface/file/displayWidgets/imageViewer.cpp
  interface/file/displayWidgets/imageViewer.h
  interface/file/fileForm.cpp
  interface/file/fileForm.ui
  interface/imagePainter/imagePainter.cpp
  interface/imagePainter/imagePainter.h
  interface/imagePainter/imagePainter.ui
  interface/imagePainter/imageView.cpp
  interface/imagePainter/imageView.h
Labels: enhancement

#132 Code refactoring
  database/test/fileTestDB.cpp
  database/test/fileTestDB.h
  drugs/dosage.cpp
  drugs/homeopathy.cpp
  drugs/medicines.cpp
  drugs/medicines.h
  interface/appointment/appointmentForm.cpp
  interface/appointment/appointmentForm.h
  interface/appointment/appointmentMiniForm.cpp
  interface/basicForms/mappTable.cpp
  interface/basicForms/mappTableSettingsForm.cpp
  interface/basicForms/tableSettingsForm.cpp
  interface/basicForms/tableSettingsForm.h
  interface/file/displayWidgets/displayManager.cpp
  interface/file/displayWidgets/displayManager.h
  interface/homeopathy/homeopathyDrugDilutionsSelectForm.cpp
  interface/homeopathy/homeopathyDrugForm.cpp
  interface/homeopathy/homeopathyDrugForm.ui
  interface/homeopathy/homeopathyDrugListForm.h
  interface/homeopathy/homeopathyDrugListForm.ui
  interface/medicine/medicineDrugBrandSelectForm.cpp
  interface/medicine/medicineDrugForm.cpp
  interface/medicine/medicineDrugListForm.h
  interface/medicine/medicineDrugReleaseFormSelectForm.cpp
  interface/medicine/medicineDrugReleaseFormSelectForm.h
  interface/patient/patientForm.cpp
  interface/patient/patientForm.h
  interface/timetable/dailyTimetable.cpp
  interface/timetable/entries/appointmentEntry.cpp
  interface/timetable/entries/eventEntry.cpp
  interface/timetable/entries/timetableEntry.h
  interface/utils.cpp
  timetable/event.cpp
  timetable/event.h
Labels: refactoring
