Repository rust379/MApp, pull requests merged in 2021-08, with the labels that each got.

#62 Change data in databaseTest
  database/databasetest.cpp
Labels: refactoring

#66 Remove openMode from patient form
  interface/appointment/appointmentForm.cpp
  interface/patient/patientForm.cpp
  interface/patient/patientForm.h
Labels: refactoring

#51 Files
  MApp.pro
  database/databaseinterface.h
  database/databasetest.cpp
  database/databasetest.h
  file/file.cpp
  file/file.h
  interface/appointment/appointmentForm.cpp
  interface/appointment/appointmentForm.ui
  interface/basicForms/mappTable.cpp
  interface/basicForms/mappTable.h
  interface/basicForms/mappTable.ui
  interface/basicForms/tableSettingsForm.cpp
  interface/basicForms/tableSettingsForm.h
  interface/file/fileForm.cpp
  interface/file/fileForm.h
  interface/file/fileForm.ui
  interface/file/filesListForm.cpp
  interface/file/filesListForm.h
  interface/file/filesListForm.ui
  interface/icons/extensions/png.png
  interface/icons/extensions/txt.png
  interface/patient/patientForm.cpp
  interface/patient/patientForm.ui
  interface/utils.cpp
  interface/utils.h
Labels: enhancement

#71 Remove private fields
  appointment/appointment.h
  drugs/homeopathy.cpp
  drugs/homeopathy.h
  drugs/medicines.cpp
  drugs/medicines.h
  file/file.cpp
  file/file.h
  interface/appointment/appointmentForm.cpp
  interface/appointment/appointmentMiniForm.cpp
  interface/file/fileForm.cpp
  interface/homeopathy/homeopathyDrugForm.cpp
  interface/medicine/medicineDrugForm.cpp
  interface/service/serviceForm.cpp
  interface/utils.cpp
  service/service.cpp
  service/service.h
  timetable/timetableUtils.h
Labels: refactoring

#72 Remove open mode
  interface/appointment/appointmentForm.cpp
  interface/appointment/appointmentForm.h
  interface/appointment/appointmentMiniForm.cpp
  interface/appointment/appointmentsListForm.cpp
  interface/homeopathy/homeopathyDrugForm.cpp
  interface/homeopathy/homeopathyDrugForm.h
  interface/medicine/medicineDrugForm.cpp
  interface/medicine/medicineDrugForm.h
  interface/patient/patientForm.cpp
  interface/service/serviceForm.cpp
  interface/service/serviceForm.h
Labels: refactoring

#73 Fix bug with save patient
  interface/patient/patientForm.cpp
Labels: bug

#76 Fix build
  interface/homeopathy/homeopathyDrugForm.cpp
  interface/medicine/medicineDrugForm.cpp
Labels: bug

#84 Fix bug with homeopathy save
  interface/homeopathy/homeopathyDrugForm.cpp
Labels: bug

#82 Fix double save (code not saved for edited objects)
  database/databasetest.cpp
Labels: bug

#80 Adjust appointment form's size to files table
  interface/appointment/appointmentForm.cpp
Labels: bug

#78 Patient small refactoring
  interface/patient/patientForm.cpp
  interface/patient/patientForm.h
Labels: refactoring

#53 Add timetable classes/forms
  MApp.pro
  interface/appointment/appointmentForm.cpp
  interface/appointment/appointmentForm.h
  interface/appointment/appointmentForm.ui
  interface/appointment/appointmentMiniForm.cpp
  interface/appointment/appointmentRecordForm.cpp
  interface/appointment/appointmentRecordForm.h
  interface/appointment/appointmentRecordForm.ui
  interface/appointment/appointmentsListForm.cpp
  interface/icons.qrc
  interface/icons/left-arrow.png
  interface/icons/right-arrow.png
  interface/icons/start.png
  interface/mainwindow.cpp
  interface/mainwindow.h
  interface/mainwindow.ui
  interface/timetable/dailyTimetable.cpp
  interface/timetable/dailyTimetable.h
  interface/timetable/entries/appointmentEntry.cpp
  interface/timetable/entries/appointmentEntry.h
  interface/timetable/entries/eventEntry.cpp
  interface/timetable/entries/eventEntry.h
  interface/timetable/entries/timetableEntry.cpp
  interface/timetable/entries/timetableEntry.h
  interface/timetable/timetableForm.cpp
  interface/timetable/timetableForm.h
  interface/timetable/timetableForm.ui
  interface/utils.cpp
  interface/utils.h
Labels: enhancement

#86 Fix build
  interface/appointment/appointmentForm.cpp
  interface/timetable/dailyTimetable.cpp
  interface/timetable/entries/appointmentEntry.cpp
  interface/timetable/entries/timetableEntry.cpp
Labels: bug

#70 MAppTable - Make table flags.
  interface/basicForms/mappTable.cpp
  interface/basicForms/mappTable.h
  interface/file/filesListForm.cpp
  interface/file/filesListForm.h
  interface/patient/patientForm.cpp
  interface/utils.cpp
Labels: refactoring

#95 Do not use non-existent signal (textChanged for additional patient info)
  interface/patient/patientForm.cpp
Labels: bug
