Repository rust379/MApp, pull requests merged in 2022-07, with the labels that each got.

#146 prodDB - Add MySQL DB.
  MApp.pro
  database/databasetest.cpp
  database/itemDatabaseInterface.h
  database/prod/appointmentDB.cpp
  database/prod/appointmentDB.h
  database/prod/config.h
  database/prod/create_tables_queries.txt
  database/prod/databaseSQL.cpp
  database/prod/databaseSQL.h
  database/prod/dbUtils/dbUtils.cpp
  database/prod/dbUtils/dbUtils.h
  database/prod/eventDB.cpp
  database/prod/eventDB.h
  database/prod/fileDB.cpp
  database/prod/fileDB.h
  database/prod/homeopathyDB.cpp
  database/prod/homeopathyDB.h
  database/prod/itemProdInterface.h
  database/prod/medicineDB.cpp
  database/prod/medicineDB.h
  database/prod/patientDB.cpp
  database/prod/patientDB.h
  database/prod/queries.qrc
  database/prod/query.cpp
  database/prod/query.h
  database/prod/serviceDB.cpp
  database/prod/serviceDB.h
  database/test/fileTestDB.cpp
  database/test/fileTestDB.h
  database/test/itemTestInterface.h
  interface/file/displayWidgets/textViewer.cpp
  interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.cpp
  main.cpp
  utils/utils.cpp
  utils/utils.h
Labels: enhancement, database

#163 Add subprojects, some MApp.pro fixes (macos sdk check)
  MApp.pro
  MAppBaseObj/MAppBaseObj.pri
  appointment/appointment.pri
  contrib/toggleSwitch/toggleSwitch.pri
  database/database.pri
  database/prod/dbUtils/dbUtils.pri
  database/prod/prod.pri
  database/test/test.pri
  drugs/drugs.pri
  file/file.pri
  interface/appointment/appointment.pri
  interface/basicForms/basicForms.pri
  interface/basicForms/components/multiColumnSortFilterProxyModel/multiColumnSortFilterProxyModel.pri
  interface/basicForms/editableList/editableList.pri
  interface/file/displayWidgets/displayWidgets.pri
  interface/file/file.pri
  interface/homeopathy/homeopathy.pri
  interface/imagePainter/imagePainter.pri
  interface/interface.pri
  interface/medicine/medicine.pri
  interface/patient/patient.pri
  interface/service/service.pri
  interface/textEditor/textEditor.pri
  interface/timetable/calendarWidget/calendarWidget.pri
  interface/timetable/dailyTimetable/dailyTimetable.pri
  interface/timetable/dailyTimetable/events/events.pri
  interface/timetable/event/event.pri
  interface/timetable/timetable.pri
  interface/timetable/timetableTop/dailyTimeline/dailyTimeline.pri
  interface/timetable/timetableTop/dailyTimeline/widgets/widgets.pri
  interface/timetable/timetableTop/timetableTop.pri
  patient/patient.pri
  service/service.pri
  timetable/timetable.pri
  utils/utils.pri
Labels: refactoring

#176 Prod db hotfix
  database/prod/appointmentDB.cpp
  database/prod/create_tables_queries.txt
  database/prod/databaseSQL.cpp
Labels: bug

#179 Prod db hotfix
  database/prod/config.h
  database/prod/create_tables_queries.txt
Labels: bug
